# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 金口碑奖投票

on:
    workflow_dispatch:
    schedule:
        - cron: "0 16 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_mgold

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: 安装依赖包
              run: |
                  npm install
            - name: "运行【金口碑奖投票】"
              run: |
                  node Ponysitters_Club_Season.js
              env:
                  JD_COOKIE: ${{secrets.JD_COOKIE }}
                  JD_DEBUG: ${{ secrets.JD_DEBUG }}
                  JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
                  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
                  PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
                  SYNCURL: /The.Flash/The.Flash/jd_mgold.js
